### ISSUE TITLE
Errors with tag phpstan.broker.dynamicFunctionReturnTypeExtension

### ISSUE THREAD

**Issue by pablorsk** [Weebly/phpstan-laravel#13]
I add `weebly/phpstan-laravel` and put `vendor/weebly/phpstan-laravel/extension.neon` on my includes list of phpstan. But when run phpstan, I get

```
Fatal error: Uncaught Nette\DI\ServiceCreationException: Service of type Weebly\PHPStan\Laravel\Utils\AnnotationsHelper needed by Weebly\PHPStan\Laravel\BuilderMethodExtension::__construct() not found. Did you register it in configuration file? in /app/vendor/nette/di/src/DI/Helpers.php:117
Stack trace:
#0 /app/vendor/nette/di/src/DI/ContainerBuilder.php(629): Nette\DI\Helpers::autowireArguments(Object(ReflectionMethod), Array, Object(Nette\DI\ContainerBuilder))
#1 /app/vendor/nette/di/src/DI/ContainerBuilder.php(575): Nette\DI\ContainerBuilder->completeStatement(Object(Nette\DI\Statement))
#2 /app/vendor/nette/di/src/DI/PhpGenerator.php(47): Nette\DI\ContainerBuilder->complete()
#3 /app/vendor/nette/di/src/DI/Compiler.php(257): Nette\DI\PhpGenerator->generate('Container_56e7f...')
#4 /app/vendor/nette/di/src/DI/Compiler.php(177): Nette\DI\Compiler->generateCode()
#5 /app/vendor/nette/bootstrap/src/Bootstrap/Configurator.php(306): Nette\DI\Compiler->compile()
#6 [internal function]: Nette\Configurator->generateContainer(O in /app/vendor/nette/di/src/DI/ContainerBuilder.php on line 589
```

The problem is with tag `phpstan.broker.dynamicFunctionReturnTypeExtension`, if remove these lines, phpstan works fine. Any ideas?

**Comment by Ascendens** [comment]
Hi, @pablorsk! I ran analyse with latest master and Laravel v5.5.40 and there is no such error. Weebly\PHPStan\Laravel\Utils\AnnotationsHelper is registered in [extension.neon](https://github.com/Weebly/phpstan-laravel/blob/master/extension.neon). Can you provide a little bit more details?

**Comment by pablorsk** [comment]
Its working now. Sorry I don't have very much feedback.

I remove all docker machine and reinstall all composer dependencies.
